### ISSUE TITLE
dev.v1 branch states that WEB UI is included

### ISSUE THREAD

**Issue by let4be** [certusone/wormhole#1090]
https://github.com/certusone/wormhole/blob/dev.v1/DEVELOP.md
states that there's a web UI however I see nothing like this in this branch, does wormhole provide built-in UI only for v2 and if so what one could use to interact with the v1 wormhole running in non-dev mode?

**Comment by SEJeff** [comment]
Hello, the v1 webui is maintained by solana labs in the [oyster](https://github.com/solana-labs/oyster) project. We would kindly ask that you do not send new funds through wormhole's v1 network as it has been deprecated in favor of the more capable v2 protocol.
