### ISSUE TITLE
Solana Transfer Native Fee is not being untruncated and collected from user

### ISSUE THREAD

**Issue by serejkaaa512** [certusone/wormhole#1098]
Amount and Fee is [truncated](https://github.com/certusone/wormhole/blob/d678cb4662f5eb9b9590c0c9e9238d137b5e4226/solana/modules/token_bridge/program/src/api/transfer.rs#L175). Amount is untruncated, but fee doesn't.

Also it is not transferred from user. As i understand, user can have no funds to pay fee, but program will work as all is ok.

**Comment by evan-gray** [comment]
Fee here is the relayer fee, a portion of the transfer (like a bounty) given to whomever redeems the transfer on the target chain. There is a [check](https://github.com/certusone/wormhole/blob/d678cb4662f5eb9b9590c0c9e9238d137b5e4226/solana/modules/token_bridge/program/src/api/transfer.rs#L148) to ensure the fee is not greater than the amount. Could you provide more detail if you still see an issue here?

**Comment by serejkaaa512** [comment]
For example, decimals = 10, amount = 1099, fee = 100.
After truncation / untruncation values would be following: amount = 1000, fee = 1.
I don't know, If it is a correct behavior and fee must be 100x times lower than in received parameters.
