### ISSUE TITLE
terra: MarshalJSON relies on undefined behavior

### ISSUE THREAD

**Issue by leoluk** [certusone/wormhole#116]
https://github.com/certusone/wormhole/blob/1ca2e29916dca3db9c39e2a7b8d0d25e8e508932/bridge/pkg/terra/sender.go#L24

Colleague pointed out that `%d` with a slice relies on an implementation detail of fmt.Sprintf (sorry for missing this during code review).

What is the purpose of this? The null behavior?

**Comment by ysavchenko** [comment]
This part is removed by migrating to base64 format for binary, see https://github.com/certusone/wormhole/pull/115

**Comment by leoluk** [comment]
Perfect :)
