### ISSUE TITLE
Unable to redeem UST (Wormhole) token

### ISSUE THREAD

**Issue by habdelwahed87** [certusone/wormhole#1171]
Hello,
Need your urgent support please, I transferred a wrapped UST from my BSC account to Terrastation using https://bridge.terra.money/ 
but not yet been received and when I tried to Redeem it gave me an error that the TXN number is invalid.

Txn= 0xa3cf22f0f14BexZMoP1gqvSbLZSfYigjUvfcXkroScK0be189389022cd7831a59

![2022-05-11_23-19-00](https://user-images.githubusercontent.com/63140389/167944476-c54b6872-802b-4cde-b2d4-fb7188a17ccb.jpg)

**Comment by SEJeff** [comment]
Your funds are safu, but we are working through the backlog and it might take a bit more time. [Please see this tweet for more info](https://twitter.com/wormholecrypto/status/1524829470238072833).

**Comment by fankeu** [comment]
Have you able to resolved your issues?

**Comment by evan-gray** [comment]
Hi @habdelwahed87, I don't see a BSC transaction matching `0xa3cf22f0f14BexZMoP1gqvSbLZSfYigjUvfcXkroScK0be189389022cd7831a59` can you verify that this is the correct transaction hash and the transaction was confirmed?

**Comment by habdelwahed87** [comment]
Thanks, yes the txn was written wrong on the wormhole website so I spent 5 hours searching for it and finally entered it manually from the url address.


Best Regards,
Hossam Abdelwahed
Sent from my iPhone

On 14 May 2022, at 9:36 PM, fankeu ***@***.***> wrote:

﻿

Have you able to resolved your issues?
