### ISSUE TITLE
requested VAA not found in store - USDC from Terra to Ethereum

### ISSUE THREAD

**Issue by thesusweatherman** [certusone/wormhole#1177]
Hello, I need some support.  I know the TERRA network has been down and I'm not sure if this is related to the Blockchain or the Luna/UST price action but I am receiving the following error "requested VAA not found in store"  the transaction can be viewed at: https://finder.terra.money/mainnet/tx/66737bf756543aebfb3967fe585afa19f7b498449760e112f51412ba5177d181 
The transaction appears to have gone through but when I try to redeem I receive the VAA error.  Any help is greatly appreciated.
Thank you

**Comment by SEJeff** [comment]
Your funds are safu, but we are working through the backlog and it might take a bit more time. [Please see this tweet for more info](https://twitter.com/wormholecrypto/status/1524829470238072833).

**Comment by thesusweatherman** [comment]
Thank you.  I have since been able to move other funds but I still receive the VAA error on this one.  I'll check back later and update.  Thank you.

**Comment by thesusweatherman** [comment]
Hello, checking in.  I just tried and still receive the "requested VAA not found in the store" error message.  Any assistance or update is a big help right now.  Thanks

**Comment by thesusweatherman** [comment]
Funds recovered...thanks so much for your help.
