### ISSUE TITLE
Requested VAA not found in store (transfer of LUNA from Terra to BSC stuck)

### ISSUE THREAD

**Issue by valenlopez993** [certusone/wormhole#1179]
Hello, I need some support please

I tried to bridge LUNA from Terra to Binance Smart Chain.
Here is the transaction on Terra : https://finder.terra.money/mainnet/tx/2BBB868997FE8AB1826AC5D0F6952A14ECA3945611EC3D6374A2574D920B2DB4

The Terra's transaction happened but when I try to recover the LUNA the flow on BSC, I am getting a "requested VAA not found in store" error.

![image](https://user-images.githubusercontent.com/82229989/168156342-e68b2f28-f258-4f2e-a6e2-9b44e7f46256.png)

**Comment by SEJeff** [comment]
Your funds are safu, but we are working through the backlog and it might take a bit more time. [Please see this tweet for more info](https://twitter.com/wormholecrypto/status/1524829470238072833).

**Comment by valenlopez993** [comment]
Thanks, I was able to redeem it now
