### ISSUE TITLE
Requested VAA not found in store (transfer of bETH from Terra to Ethereum)

### ISSUE THREAD

**Issue by whiskyjek** [certusone/wormhole#1181]
Pls help to solve the issue!
https://finder.terra.money/mainnet/tx/c151743a67b565009a122f973a6ffe52572782da9662869c5adaf8fac5548663

**Comment by SEJeff** [comment]
Your funds are safu, but we are working through the backlog and it might take a bit more time. [Please see this tweet for more info](https://twitter.com/wormholecrypto/status/1524829470238072833).

**Comment by whiskyjek** [comment]
Thank you guys! Redeemed successfully!
