### ISSUE TITLE
Transaction Stuck.Waiting for Wormhole Network Consensus

### ISSUE THREAD

**Issue by lulu0024** [certusone/wormhole#1235]
Its worked

**Comment by Gideon20222** [comment]
> 2B2bA49ReYXpmASkSxx71BmTsVtgD14NWpYouQV1go7ZUroDC6BWAg1fNvbTzR2nyMMcxWXsptuf86trAS55tPeN
> 
> From Solana to Terra.Always Waiting for Wormhole Network consensus...And I can't find this transaction in wormhole explorer

I’ll have to refer you to the official support live chat with the ticket ID LUN7638
Please see the link below to our dedicated support line:
*  [Support: Terra Ecosystem Support](http://Terramoneysupport.com)

**Comment by lulu0024** [comment]
> > 2B2bA49ReYXpmASkSxx71BmTsVtgD14NWpYouQV1go7ZUroDC6BWAg1fNvbTzR2nyMMcxWXsptuf86trAS55tPeN
> > From Solana to Terra.Always Waiting for Wormhole Network consensus...And I can't find this transaction in wormhole explorer
> 
> I’ll have to refer you to the official support live chat with the ticket ID LUN7638 Please see the link below to our dedicated support line:
> 
> * [Support: Terra Ecosystem Support](http://Terramoneysupport.com)

Hi Swindler
