### ISSUE TITLE
SyntaxError: Invalid or unexpected token

### ISSUE THREAD

**Issue by koraixayo** [certusone/wormhole#1308]
While using the SDK, it shows the error that invalid or unexpected token was found in

@certusone/wormhole-sdk/lib/cjs/solana/core/bridge_bg.js:24:2

<img width="782" alt="Screen Shot 2022-06-26 at 11 01 01 PM" src="https://user-images.githubusercontent.com/81546175/175826051-f9ae90bd-73a8-4848-bc70-315a851e6e7d.png">

**Comment by evan-gray** [comment]
If you're in node, try `setDefaultWasm("node");`
