### ISSUE TITLE
terra: do not keep state for invalid VAAs

### ISSUE THREAD

**Issue by leoluk** [certusone/wormhole#142]
[Kudelski audit finding for the Everstake Terra audit]

The Terra contract adds VAA hashes to the list of processed VAAs as soon as they're received, regardless of validity. This opens up the possibility of an attacker to fill up the memory by sending random VAAs and also to block certain VAAs by sending them unsigned before the guardians signed them.

Invalid VAAs must be discarded without keeping any state about them.

**Comment by ysavchenko** [comment]
VAA hashes are written to the storage early on, but this write gets rolled back on error. So at the end invalid VAA hashes will not be stores.
