### ISSUE TITLE
Polygon Support

### ISSUE THREAD

**Issue by CrisBRM** [certusone/wormhole#200]
As per our conversation, main considerations are:

- Existing contract can be re-used

- Guardian set must be convinced to run a node for the new chain and take on the additional operations load
  - Could Polygon's validators create their own guardian set?

- Adding support for the new chain to guardiand (polygon supports Ethereum's RPC)

-  Finding a working incentivization model
  - Polygon Foundation and Terraform Labs would likely subsidize this
  - 0.025-0.05% fees of amount transacted would likely not be objected to by users of the bridge

**Comment by leoluk** [comment]
> Could Polygon's validators create their own guardian set?

Yes - Polygon's validators could launch a separate Wormhole network. If it's 100% EVM/RPC compatible, this may even be possible without any changes in the code base

**Comment by evan-gray** [comment]
closing as polygon is now one of the supported chains.
