### ISSUE TITLE
Is it possible to reverse a transaction that was done on the wormhole demo?

### ISSUE THREAD

**Issue by jocot** [certusone/wormhole#201]
Myself and someone else decided to test the wormhole demo, by sending some KIN tokens across to Solana, which were received, but were wrapped as unidentified tokens on Solana.

Just wondering if it's possible to send those tokens back from Solana through the wormhole and receive the original KIN ?

Thank you.

**Comment by hendrikhofstadt** [comment]
If you transfer the wrapped tokens back to ETH it will release the original tokens
