### ISSUE TITLE
HBTC SOL TO ETH  READING BUG

### ISSUE THREAD

**Issue by yclnl** [certusone/wormhole#220]
The reading is incorrect. It can't show the correct balance. 
I think this is UI bug.

**Comment by yclnl** [comment]
<img width="1243" alt="bug" src="https://user-images.githubusercontent.com/4837860/126112762-deab259a-ff3c-470f-848d-09357267c8c8.png">

**Comment by yclnl** [comment]
<img width="1244" alt="bug" src="https://user-images.githubusercontent.com/4837860/126112888-ed3ffac2-2dc9-4dd8-abd3-dd8b6757520d.png">

**Comment by hendrikhofstadt** [comment]
This UI was not developed by us and we can't support it unfortunately. I'm sorry, we can't help with issues there.

**Comment by yclnl** [comment]
Is this website:
https://www.wormholebridge.com/
not developed by you.

**Comment by hendrikhofstadt** [comment]
No it was not developed by us, we just built the bridge backend and someone built this frontend for it

**Comment by leoluk** [comment]
@bartosz-lipinski

**Comment by leoluk** [comment]
You can create issues for wormholebridge.com here: https://github.com/solana-labs/oyster/issues
