### ISSUE TITLE
Stuck/Missing Tx

### ISSUE THREAD

**Issue by thenightman12** [certusone/wormhole#224]
I tried using the wormhole via Sollet to move 300 USDC from SOL to ETH and the SOL transaction shows confirmed: https://solscan.io/tx/2XvcAC5pyRV14LwrUvXyekcE1popJezMccGLePK2LRtt3hs4C7Pzn6XVNudtV4WdHeg7nTDD1C2dLRWGopFh2SBX

The SOL transaction (link above) confirmed about an hour ago but I can't find/see the equivalent transaction on ETH. I've been monitoring the Solana Sollet Bridge contract on Etherscan but have yet to see my transaction.

**Comment by leoluk** [comment]
Sollet is using a centralized bridge operated by Serum/FTX which is unrelated to Wormhole. Try Serum's Discord.
