### ISSUE TITLE
Wormhole transfer

### ISSUE THREAD

**Issue by bobe8** [certusone/wormhole#249]
I never got my coins. I transferred 1 busd from eth to solana using the bridge. Here is the tx:
https://etherscan.io/tx/0x9f96b887b0c33353044b48ac3694b6cc2844a903b9fe12ae8a4b25dbbc6a8a15

**Comment by hendrikhofstadt** [comment]
Completed in https://explorer.solana.com/tx/4obSeQBWHXUB7gbeEoep5kWxNByysZWuL8zkk2k7j6xQvQnqyrCu77Qg2maKhgqCh3X5wfSLN6ih1oNGKV11dJJf
