### ISSUE TITLE
Wormhole Transfer Lost

### ISSUE THREAD

**Issue by phannypharkle** [certusone/wormhole#250]
Attempting to send Wormhole RenBTC from Solana to Ethereum. Was able to approve and submit the tx on Solana and then it failed somewhere. I don't see my RenBTC balance on Solana or Ethereum now

https://explorer.solana.com/tx/2eRAzfqkwss2PSvS9mmAAtUD8aHyHAsvTPV2Jkrp9PKCqCSPPn6aduFdGT7FqirvpqpWZRgrGkEVp96BHeNF4XJy

https://explorer.solana.com/tx/5rFXZWyoKGbJzUNyqHg4SmSYS57yUQ4SRCtRF8Y17egs5b9fy2jxukqq9NvPNAS6LNkd3n6Ev2P3bmhxJfHxKwPp

**Comment by hendrikhofstadt** [comment]
The wormhole attested your transfer correctly (https://explorer.solana.com/tx/2oi3uPnoH46aTabPcB8f8UNsKGMNdmFmpteDKxC1j4tweUHg2qWRZWauNbsRYyorczGGeAExufJDbCF1y9BZYHb3), please consult with the developer of the UI to complete your transfer. We don't provide or support any UIs for token transfers right now.
