### ISSUE TITLE
Wormhole tx stuck

### ISSUE THREAD

**Issue by bellabartok** [certusone/wormhole#251]
I tried bridging renBTC from ETH to Solana and the tx never completed. Tx ID is 
0xc2a5858925a4184baa3abba4a6ddea28221335ba06b7d2176d9e2f15fe205

The renBTC left the ETH wallet but never made it into my phantom wallet.

**Comment by hendrikhofstadt** [comment]
The transaction hash you provided is not correct.

**Comment by bellabartok** [comment]
Hi, sorry, must have copied something different. Attaching screenshot:

[image.png]

Copy pasting tx -- 0xc2a5858925a4184baa3abba4a6ddea28221335ba06b7d2176d9e2f15fe2050eb

Sent with [ProtonMail](https://protonmail.com/) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by hendrikhofstadt** [comment]
You sent the token to a non-existing account. Not sure how you did it (maybe the UI you were using was broken) but the address the tokens were sent to (https://explorer.solana.com/address/FPV4RvtUvShnGAp1ADLPdZfEspj9szobBr64ekYMX4RY) is not a token account.

I obviously don't need to explain to you that unless you hold the keys to this address your tokens are lost (i.e. you transferred them to the wrong address).

**Comment by bellabartok** [comment]
Guys, I used the bridge! I didn't send anything anywhere, but used the actual wormhole bridge! It was processing the tx just fine and got to nearly the last step before my Internet dropped and the progress stopped updating.

I used the same exact bridge to send pbtc to the same exact wallet right before, and it arrived there, though there it shows up at "unknown token." Please help me fix this.

Sent with [ProtonMail](https://protonmail.com/) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by hendrikhofstadt** [comment]
I see that you used the bridge. However you specified FPV4RvtUvShnGAp1ADLPdZfEspj9szobBr64ekYMX4RY as target address for the tokens on the other side of the bridge. This is where Wormhole wants to send the tokens. However that wallet does not exist.

**Comment by bellabartok** [comment]
I don't know how because I used the same exact wallet. Can we reverse the tx?

Sent with [ProtonMail](https://protonmail.com/) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by hendrikhofstadt** [comment]
It's as if you sent assets to the wrong recipient. I'm sorry there's no way to reverse the transfer.

**Comment by bellabartok** [comment]
I'm sorry but I cannot accept that. I used your bridge, your tech, exactly as it functioned. I grief a test TX first and it worked. You can't tell me now that I lost 2 btc because somehow your bridge malfunctioned. If the coins are still in the bridge waiting to be sent, I'm sure the TX can be reversed.

**Comment by bellabartok** [comment]
You guys must take responsibility for issues resulting from broken UI. How could the coins have been sent to a non-existing address? I copy pasted my private address. I know that you have plenty of options with SOL, we're not talking about BTC here.

**Comment by leoluk** [comment]
> You guys must take responsibility for issues resulting from broken UI. How could the coins have been sent to a non-existing address? I copy pasted my private address. I know that you have plenty of options with SOL, we're not talking about BTC here.

Wormhole is a decentralized protocol - it has no UI, it's a set of on-chain contracts that expose an API for third party UIs like wormholebridge.com or wallets to use.

Solana addresses in particular have no checksum, so it's impossible to determine whether an address is valid or not. If a UI calls Wormhole specifying an invalid destination address, then Wormhole is going to send the tokens to that address. It's like calling an Eth contract with wrong parameters.

Could you describe exactly what you did? Which addresses, what wallet did you use, which UI did you use to do the transfer?

**Comment by bellabartok** [comment]
I used the bridge at this link (https://www.wormholebridge.com/#/move?from=ETH&token=WETH), put in the token (renbtc) from ETH to SOL. I had just done a test tx with pbtc and it arrived to my phantom wallet fine, though as an "unknown token" instead of "pbtc." Still, the amount matched so I figured I'd deal with the designation issue later. I'm attaching a screenshot of what it looks like in my wallet.

I then sent the full 2 renbtc to the same phantom wallet address. The tx went through all the steps and then seemed to get stuck at the second to last step, wheel spinning for longer than the previous tx. I lost wifi after a while, and when I got back online I had to refresh page, at which point I couldn't see the status/steps any longer.

Please understand that I could not have given a different address than 8aAwGy74SFyACbaBx6keUz2J2y8jb7M9LRBm6mvMSRVQ. It is the only SOL address I have. I have no other wallets I could have possibly sent this to.

If the bridge somehow corrupted the tx and sent it to some random address, that is a MAJOR problem with your tech that caused me to lose a whopping 2 BTC. I am very much hoping this isn't the case. It would be one thing if the mistake was mine, but it wasn't. You can't just shrug it off as an "oh well" and expect me to accept it.

Sent with [ProtonMail](https://protonmail.com/) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by hendrikhofstadt** [comment]
It sounds like the UI failed to create a token account (as you probably know on Solana you need to manually create accounts for each token) but still proceeded to let you transfer tokens to said wallet (which is the equivalent to generating a new key/address and forgetting it right after but still sending assets to it). If the UI you used uses associated accounts, you might be lucky because you can gain access to said account. If not and the UI did not cache the key to said wallet, I think there's nothing you can do about this right.

I want to stress again, that Certus One has **NOT** built and does not publicly endorse or advertise the UI you used. This UI was built by another team and given that the Wormhole protocol correctly processed the transfer (just like ETH would if you sent funds to a random wallet you don't own the key to), we can't help you in this situation.

I'd recommend you to open a ticket here https://github.com/solana-labs/oyster/issues which is the repo where the UI code is. As you can clearly see, none of us has ever made a contribution to this code base.

**Comment by bellabartok** [comment]
I'm not technically shrewd so be verifying those things. All I know is I was referred here for any bridge related issues.

First things first, please tell me how to check whether I might have access to that address? When I open phantom, I only see one receiving address. So how do I check?

Sent with [ProtonMail](https://protonmail.com/) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by bellabartok** [comment]
Looks like other people are losing their coins.

[image.png]

Sent with [ProtonMail](https://protonmail.com/) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by bellabartok** [comment]
It was a moderator from the Solana discord who told me to open a ticket on your github. Solana is managing issues with the bridge, even if another team built it. This is a huge amount of $ and I would appreciate every effort to help me recover it.

Sent with [ProtonMail](https://protonmail.com/) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by bellabartok** [comment]
Is anyone still reading this?

Sent with [ProtonMail](https://protonmail.com/) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by bellabartok** [comment]
It is not acceptable to just wash your hands off this issue, guys. I will open a ticket myself on that page but I will also make sure all the crypto communities I'm part of are aware of the insane risk of using Solana approved tools.

Sent with [ProtonMail](https://protonmail.com/) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by leoluk** [comment]
Like Hendrik said, this is not a Wormhole issue, but a bug in a wallet/UI which none of us have contributed to. It's a bit like contacting the Ethereum core devs about a Metamask issue. Losing tokens sucks (even temporarily) and we'll do our best to help the UI's developers to figure this out and help you get your tokens back, but we can't fix it.

The Solana Labs engineers who built wormholebridge.com are in a much better position to debug this and complete the transfer, and I'm sure they'll be glad to help now that you contacted them.

The way SPL tokens work, you need a dedicated token account for every mint you want to receive tokens for. It appears that in your case, there's no transaction to create the token account, but a transaction that sends tokens to it, and therefore, it fails.

Right now, this account doesn't exist:

```
$ solana account FPV4RvtUvShnGAp1ADLPdZfEspj9szobBr64ekYMX4RY
Error: AccountNotFound: pubkey=FPV4RvtUvShnGAp1ADLPdZfEspj9szobBr64ekYMX4RY
```

We don't know how the UI works. Most likely, the token accounts are derived deterministically, in which case it should be possible to derive the same key the UI did, create the missing token account, and then retry the VAA submission. Once you have the token account, we can - of course - help you manually resubmit the VAA to complete the transfer.

(x-ref https://github.com/solana-labs/oyster/issues/161)

**Comment by bellabartok** [comment]
Thank you, that gives me some hope. My ticket number is 161, I hope to have a good update soon.
