### ISSUE TITLE
withdrew RenBTC from solana to ETH but only got Wormhole Wrapped Token, How do I send it back?

### ISSUE THREAD

**Issue by misterbaka** [certusone/wormhole#252]
Hi,

I bought some renbtc on solana and used wormhole to send it over to ETH. I didnt expect to get a wormhole wrapped token which is useless on ETH. I want to send it back but I dont see a way to bring up that token on the wormhole UI.

token: https://etherscan.io/token/0x18b6b94f185ccf3ca721432a1e9ebf28bb8472c3

Can someone please help?

Thanks!

**Comment by hendrikhofstadt** [comment]
Please consult with the developer of the UI to transfer the tokens back. Please note that we neither provide nor support any Wormhole UI. The Wormhole did not malfunction. It is a different bridge than ren and can therefore not bridge native ren tokens in an unwrapped form.

**Comment by misterbaka** [comment]
who is the developer of the UI? when I select help on the UI page it sends me to this github..

**Comment by leoluk** [comment]
You can create issues for wormholebridge.com here: https://github.com/solana-labs/oyster/issues
