### ISSUE TITLE
Lost wUST in bridge from ETH to SPL wallet

### ISSUE THREAD

**Issue by CryptopunkCory** [certusone/wormhole#255]
Transferring wUST using wormhole from my ETH wallet to my SPL wallet, got to 14/15 transactions and awaiting final confirmation on Solana.

This morning I checked the transaction and wUST is not in my ETH wallet or SPL wallet now.

Please advise!

https://solscan.io/tx/2aqjRquB6j2F9kSmHN6Ph5PTBPpg9km4GxnCEBGwoJUToz5H8rLCjmwnw3jatfLSSnck1Hk1HTHHmbbKnga6G4zq

https://etherscan.io/tx/0xe33012376944b5e32d998b19aa2bf2eb3d8dc75e0edde1cc056397b6fa99088d

**Comment by hendrikhofstadt** [comment]
Completed in https://explorer.solana.com/tx/2xXtpgGcbS5bLJPTGMmdV9pjdL5ssLLQHU3W6tF1y2it1KrfyfQcDmNTuRxnr6QgC4XYokygrLwsKMr2uPcJG1Ko
