### ISSUE TITLE
wMEDIA is not displayed on wormholebridge.com

### ISSUE THREAD

**Issue by DMan326159** [certusone/wormhole#256]
I sent MEDIA tokens using Wormhole (SOL -> ETH):
https://explorer.solana.com/address/51aeR7a5HJ6Hza4cXgAKnZpBvUhb3LQHwtoYRs8Toms4

Got the tokens wrapped:
https://etherscan.io/tx/0x26319c9fe7b236aaa6e3f71076864478c236180d81f2e2deaa44789c7375ec7a

I want to send them back using Wormhole (ETH ->SOL), but my wMEDIA token balance shows as zero on the website. I have tried both MetaMask and WalletConnect, but the balance still shows as zero.

In reality, the tokens are present in the wallet:
https://etherscan.io/token/0xcb65d3c25e724e36609f9f7921c418af07fac6a1?a=0x6a435e3fd842b76b266208ccbf96febf143d39ed

![image](https://user-images.githubusercontent.com/9461734/126882073-8c5149e0-9f12-4d3e-8112-8d56ad7f0763.png)

**Comment by hendrikhofstadt** [comment]
We did neither develop nor do we support the UI you are using. Please get in touch with the developer of the site for support.

**Comment by DMan326159** [comment]
> We did neither develop nor do we support the UI you are using. Please get in touch with the developer of the site for support.

Can you tell me who I can contact? The website only lists your Github. Can I send tokens back without using this interface? Please tell me how we can return the funds, there are about 4 of us already?

**Comment by DMan326159** [comment]
> We did neither develop nor do we support the UI you are using. Please get in touch with the developer of the site for support.

I sincerely hope this site is not a hoax. Can you tell me the following:
1. I used this interface to interact with the real wormhole contract, right?
2. Are the tokens I received on the Ethereum network valid?

**Comment by leoluk** [comment]
Yes - the site is legit and operated by Solana. It talks to the real Wormhole contract.

You can create issues for wormholebridge.com here: https://github.com/solana-labs/oyster/issues

**Comment by DMan326159** [comment]
> Yes - the site is legit and operated by Solana. It talks to the real Wormhole contract.
> 
> You can create issues for wormholebridge.com here: https://github.com/solana-labs/oyster/issues

Thank you so much!
