### ISSUE TITLE
Stuck Transaction

### ISSUE THREAD

**Issue by the-wandering-aengus** [certusone/wormhole#258]
I've had a transaction stuck since yesterday (0.01 ibBTC). It has left my ETH wallet:

https://etherscan.io/tx/0x69b68437512a366b82cb1ad987d14f98a571fb812204b2210e94e8d987b5ede9

But not arrived in my SOL wallet (address: 8LXpW8fPk757j5zMGnkLYFaPP46MrmtnG5H8W3LcsbNh). It has been stuck on 'Awaiting Completion on Solana'. See screenshot below.

![image](https://user-images.githubusercontent.com/57923061/126903050-763f8b4d-e574-4a9a-a298-f3558358808d.png)

For reference here is the approval transaction I made in my SOL account:
https://explorer.solana.com/tx/2Q1h6oz5nAyVLi8jCrqkvFuLuFkeXHwn6v8TEeWwRb62ww2ps5dJsWAAbyfuWBPjT9Zv6VTNG8BAxYn6d3PRt6ah

**Comment by hendrikhofstadt** [comment]
Completed on Solana https://explorer.solana.com/tx/53KGGf6Sr7X8kuddppEWyQ8Z1C1rF357xbr2EF4T2nKuM4t3U4GUKvK5r4zTL4FqBgRD7vfXrAYvCFjpRfHciJxP
