### ISSUE TITLE
pBTC token not appearing in Wormhole Bridge

### ISSUE THREAD

**Issue by tomquirk84** [certusone/wormhole#259]
I believe this is a bridge issue not a wallet issue as I have used two different wallets.

1. Used the wormhole bridge to send pBTC (ptokens Bitcoin) from Ethereum to Solana
2. I now have the new pBTC in my Solana wallet - address DCXCyQpqDmedRyi6iF3Ra7V6WiFNFwHftGYeWEdtkCLY
Transaction ID - https://explorer.solana.com/tx/4fdj36EaQsrLwKvMuoufFHb523R3sUbiCbytZ22FU1jXkzvj3CyWniFBXEdVgugo2mRtAA7ekwyNV2PgMqY4tYcu

3. I wanted to deposit these into the Saber protocol, but realised the pBTC there is actually 'Parrot' BTC, so wanted to bridge them back to Ethereum.
4. I connected my Sollet wallet with the correct address and noticed that my balance shows as zero in the Wormhole bridge UI
5. I thought it might be a wallet issue, so I downloaded Phantom wallet, restored from an existing seed phrase and connected this with the same Solana address that the new pBTC tokens were, but the balance still shows as zero.

I believe many others having same issue but with other tokens.
Thank you

**Comment by hendrikhofstadt** [comment]
We have neither built nor do we support any UI for the Wormhole. The protocol itself is able to bridge any token but we don’t control what the UI you are using shows.

From what I can see your wallet holds the tokens https://explorer.solana.com/address/BzWcNWuom9HRLgJt5Z6D2qfboAprWbFGxxNhwoKjxCBz

**Comment by tomquirk84** [comment]
Thank you, I can see I hold the tokens in my wallet, but right now there's nothing that can be done with them.

They cannot be bridged back to ETH because they do not appear when the wallet is connected.

**Comment by hendrikhofstadt** [comment]
Have you tried manually entering the token address in the bridge Ui?

**Comment by tomquirk84** [comment]
Yes, when I do this nothing comes up, like it would in Uniswap etc

**Comment by hendrikhofstadt** [comment]
@bartosz-lipinski Can you please help this user with the UI?

**Comment by leoluk** [comment]
You can create issues for wormholebridge.com here: https://github.com/solana-labs/oyster/issues
