### ISSUE TITLE
wUST is not completed swapping on wormholebridge.com 

### ISSUE THREAD

**Issue by clix5cash** [certusone/wormhole#261]
Hi There,
I have sent UST (ETH) to get wUST(Solana) using wormholebridge.com and now stuck as no wUST in Solana wallet.
https://etherscan.io/tx/0x144cda922be1ff0541e8c671f2412f622cd9801dd4624b8a168571740142e7f4
There is no wUST on Solana
https://solscan.io/account/HXPis1YH5Pd8qhih4s3ysWw4Fhx9Ld9nBVg91Ufc23J
and There is no transaction record shown on my recent transaction on wormholebridge for 12 hours.
Could you please take a look and fix this?
Thanks
![Screen Shot 2021-07-25 at 19 56 59](https://user-images.githubusercontent.com/19966116/126920895-db65e49e-45cc-44dc-9057-fbf7ca6e2e41.png)

**Comment by hendrikhofstadt** [comment]
Completed in https://explorer.solana.com/tx/4eLhTdoPDy8GTr4F2MqSd2mZu58V9ejL6c4xHba1GRpdogQvEu8zeFDwmTr6Jorz1gejrbhcvjc8PDGN8GE3i2Ny
