### ISSUE TITLE
Wormhole LUNA transfer has not arrived 

### ISSUE THREAD

**Issue by cryptorus17** [certusone/wormhole#270]
I was using Wormhole to transfer 430.94 LUNA from Eth to Sollet wallet. The transaction was a "success" transferring my funds from Eth to this contract "0xf92cd566ea4864356c5491c177a430c222d7e678".
Although I'm not able to locate my LUNA in my Sollet wallet. 

Eth Transaction hash 0xd099d465532b499987b8fe73922ec8dcb5d81c5997bfaa1489adfa82e539476b
Eth transfer from 0x0be833cF3c2B9d692c7859f06da9ef0e151B8a33
Transfer to (Sollet wallet) 4Uu6JW78DsfsJfV8N5vdRfPEtq41Vg972Y7E5fu2FKjK

Need help locating my Luna. Thanks

**Comment by hendrikhofstadt** [comment]
You tried to send LUNA to a UST wallet: https://explorer.solana.com/address/HZkMPFrQLgen2GfU2XtjVvUjakJWUiJn3XUWxTxqndwS

Wormhole actually processed your transfer but given that the recipient address is not for the right token your tokens were not delivered. There is no way to recover from this. Please refrain from using the Wormhole contracts manually if you're not very familiar with the concepts of both Wormhole and Solana.

This is the same as sending funds to a wrong address on Ethereum. Please note that on Solana you have a different token account address for each token.

**Comment by cryptorus17** [comment]
[](url)

I did another transfer to the same wallet, everything is the same, received my transfer with no issue. 

https://etherscan.io/tx/0xd099d465532b499987b8fe73922ec8dcb5d81c5997bfaa1489adfa82e539476b (Not received) 
https://etherscan.io/tx/0x03fb27260c2def33bcbe21396cb00637cb4cb5b02fdefd21fb70a96b31489b53  (Received) 

<img width="1355" alt="Screen Shot 2021-07-28 at 7 36 50 AM" src="https://user-images.githubusercontent.com/88086309/127341982-3b83731a-f72e-42e8-a9ff-b61fc9751093.png">

What you are saying doesnt make sense. On Wormhole if you are choosing to transfer an asset from Eth to Solana, you can't choose LUNA on Eth part and UST on Solana side, the moment i choose LUNA on the sending side the same asset automatically fills up on the receiving side.
