### ISSUE TITLE
Re-deploy hk7 as Raydium

### ISSUE THREAD

**Issue by linuskendall** [certusone/wormhole#296]
HK7 should be re-deployed as Raydium.

It has been removed from DNS from previous pools, so it can be safely re-deployed now.

Once completed, notify me and I can put it live in DNS under the Raydium pool.

**Comment by linuskendall** [comment]
My bad, fat finger on the github tabs! Please delete @leoluk  :)

**Comment by leoluk** [comment]
Aaand it's gone :)
