### ISSUE TITLE
Please whitelist IVN token for V2 launch of wormhole

### ISSUE THREAD

**Issue by aak-dev** [certusone/wormhole#300]
We have built a decentralized fund management protocol on solana and working on deploying v2 version of our protocol. You can find more details @ https://twitter.com/Investin_pro. 

The token is available on bsc and ethereum blockchains, we use anyswap protocols bridge to move IVN from bsc to eth. Do let me know if the bridge from bsc to solana is possible earlier if not we can go with eth to solana bridge first. 

Eth erc20 address: https://etherscan.io/token/0xd22a58f79e9481d1a88e00c343885a588b34b68b
BSc erc20 address: https://bscscan.com/token/0x6a46d878401f46b4c7f665f065e0667580e031ec

**Comment by leoluk** [comment]
No need to whitelist - any ERC20/SPL token will work
