### ISSUE TITLE
Implement token picker

### ISSUE THREAD

**Issue by hendrikhofstadt** [certusone/wormhole#323]
We should implement a token picker that picks from:

Ethereum: https://tokenlists.org/
Solana: Query TokenAccounts of the connected wallet
Terra: https://assets.terra.money/cw20/tokens.json
BSC: https://bsctokenlists.org/

Or a manually entered address.

**Comment by evan-gray** [comment]
Solana has this natively. Using Covalent for Ethereum (and later BSC). Both those are in. Terra TBD.
