### ISSUE TITLE
Deploy Token Bridge v2 contracts to Testnet

### ISSUE THREAD

**Issue by hendrikhofstadt** [certusone/wormhole#324]
We'll only deploy them to Ethereum, Solana and Terra as we use BSC mainnet as testnet and don't want to cause confusion.

**Params:**
Emitter address: `0x0000000000000000000000000000000000000000000000000000000000000004`
Emitter chain: `0x01`

Alternatively we could set the emitter address to an address we control which we can use to manually emit messages. Would be a nice test run and maybe even more convenient :man_shrugging: 

Testnet currently runs in single guardian mode so we can use the Certus key to produce the `RegisterChain` VAAs.

**Comment by wormat** [comment]
What's the reason for using BSC mainnet as testnet? Without context it seems much more confusing to do it that way.

**Comment by evan-gray** [comment]
Thanks for pointing out this was still open. This has been resolved with the new (and improved) testnet that was recently deployed. https://docs.wormholenetwork.com/wormhole/contracts#testnet
