### ISSUE TITLE
Lost renBTC using Solana Wormhole

### ISSUE THREAD

**Issue by ShepStax** [certusone/wormhole#358]
I sent renBTC from ethereum to Solana, no problem there except it was unrecognizable on Solana. So, I tried sending it back but didn't have enoght ETH to complete the transaction so I rejected the contract. Now, my renBTC is gone. Not in my Solana wallet, not in my Ethereum wallet. Please help.

**Comment by leoluk** [comment]
This sounds like an issue with wormholebridge.com, rather than the core network. Please create an issue here, including transaction hashes: https://github.com/solana-labs/oyster/issues
