### ISSUE TITLE
wormhole SRM tokens sent from sol to eth didn't arrive

### ISSUE THREAD

**Issue by Investtony** [certusone/wormhole#359]
Hello, sent 2 transactions one with 272 SRM and then 0.1 SRM. Both left, only second with 0.1 SRM came to metamask.
please help with the first one 
https://explorer.solana.com/tx/5G9PTR6S46Tw53q7Jeb7xK7MCfiLAjqW4ZUeMKpg9gcRtH9iAWygAQvDtj4VMHnnCJPqY8k56Msv7EkBSHdqvxzR

much appreciated

**Comment by leoluk** [comment]
The transaction was successfully processed by the Wormhole network, but the client-side transaction submission may have failed. Try clearing your cache and reloading wormholebridge.com to see if the transaction can be completed there. Make sure both wallets are connected.

If wormholebridge.com doesn't work, you can manually submit the signed VAA bytes below to the submitVAA method on the Wormhole contract: 1https://etherscan.io/address/0xf92cd566ea4864356c5491c177a430c222d7e678#writeContract

---

Digest (for reference only): 9d0965a1e2047a97cd9589427834f4d0f7feb6b62acfa12b00178dc409ef4b58

Signed VAA bytes to submit to the contract:

> 0x01000000010d00adfde1ffa61166708d6c24f862239635b1b34156d490c4bbe4c04a3fde07125145aad30807ac8c96864763517e744cc08eca574ab2c68fd1945d81d7cc9158ef000198a24617f72344d4b4b9278022574ed0968b4a22c158e594cab767b8c2d4152f6e833038a2fcd6d3e7c84a90a7fccc652f66aa198c32797c54739cb1d6d39aa700025b55f4e43e2f8832920553cd50cd40c8f89c0fe95154fe53ee3d63cd8c4cda7844290826f842cbbca68213b23363c491f94f8c9caa5585855188787c2fc70acc0003aea008911c68f599c2135c5aea84d1decdb906b8bfc102658d94b91c422e85f67bbbeccb519527308e8438b4a93aba978a8bc6d5d43242c8e3eb9b3e85ee9d7800059724875e45752f665f4605cbfdbbbe2657bf36100868613d7b1ae7043c260d707d8fa7a81eb89d92526f6ed72e6a25094a62ca05b097fc04993394ea82b5b56f0107326a4fa532fd8a5522260911e6d91973131784e71ac74df710d4eeed052e1ae404d8de34c39e1f7e26f483ec19841d6a9ab098c6be06acf8c9455a9b6ddf32520008971a8abb655d81f5aaeeeaa20bf2f340d5e901be998e857ce8e0e04216a9281773f409f049cc201fb5143ab54f7e0f59198a51803bc39d1889da14d4cf706dff010946aece93b6d1ca42863952bb4039982c00fba61de741eb85676ce17b1b27b3cf22f43fffbe8c1cb8999265de1bc5974cf5719ca7ee52403268b9cef93a876462010a825f9ad8e0d2ae1f3d77bb0e5c79107971bb57229c44bd464a2ae50667edc3f47cff3629228d2a021cd75e099f15bcef130c6acaa3ce351d8be8c4c0b7ca36bb010dd86f19173882e60cc788738677c5de760aa03348599a7238e82dedfd8a484c40421445f45b6fcb1731a5869ad2d55b76c15387ab188f43cff995d48f851609c90010787e1df247adbaed61a13cbf820e4cdc4f97c5b0a1829e911b6ec226071ba714134c34dda8f4096558cce31d8656bafc6e3829dde0b96bc485c8202d87c95cd80011ea60e68534cb56f3a3e87d59e5c9906f8d017a5833d1b2845bfa747612c508b612c2dfb56ee95b43390fc97d970a355ca4e4cd53b76853ff8d5845f2781391eb011291b0debc6ab7027eb7c9d60a684f3f8f23a23467d0dcaee7dc3e1e2c0b03b8d74fcc1a7e224548b8b613e4b6230b7e8ca0692ad8e87edcf1e5329d43d708c31e00612e43881000010bf3010269b836a909b26b0c8b92e366c850f55664ad1f770bc00b4d2d047668722fc8ee000000000000000000000000b8a6b2a4c492eb20686ac1706bc5a2548a9e400002000000000000000000000000476c5e26a75bd202a9683ffd34359c0cc15be0ff060000000000000000000000000000000000000000000000000000000010366400
