### ISSUE TITLE
Explorer generation fails

### ISSUE THREAD

**Issue by allenan** [certusone/wormhole#378]
Following the instructions in https://github.com/certusone/wormhole/blob/dev.v2/DEVELOP.md, I get the following error from the explorer container:

```
failed Building static HTML for pages - 2.478s

 ERROR #95313 

Building static HTML failed

See our docs page for more info on this error: https://gatsby.dev/debug-html





  Error: /app/public/render-page.js:1
  TypeError: _proto_publicrpc_v1_publicrpc__WEBPACK_IMPORTED_MODULE_15__.Publicr
  pcClientImpl is not a constructor
  
  - network.tsx:46 eval
    webpack-internal:///./src/pages/network.tsx:46:17
  
  - render-page.js:30371 Module../src/pages/network.tsx
    /app/public/render-page.js:30371:1
```

Looking at that code to see why `pcClientImpl` is not a constructor, I do not see any generated js from the proto file, and looking at the script in package.json, I see a reference to `"generate-protos": "../generate-web-protos.sh",` but I do not see any corresponding `generate-web-protos.sh` file.

**Comment by leoluk** [comment]
https://forge.certus.one/c/wormhole/+/1304
