### ISSUE TITLE
Another wormhole tx stuck

### ISSUE THREAD

**Issue by bellabartok** [certusone/wormhole#379]
I was bridging wbtc back from SOL to ETH. The tx made it to the "waiting for guardian" step and just lingered there forever, never making it to my ETH wallet.

This is the tx: https://explorer.solana.com/tx/3hYMSQNXcHZjb4rSZCPtTX16qmiL63RdBCTYh3Vk1UiKek2XUKM1Q6uz87yp4oqkPYR9jVYEzJkdQQ9nxbQGEsMf

Please help me recover it...

**Comment by hx8888979** [comment]
Hope you already resolved it, or you can try my script https://www.interstellar.tk/

**Comment by leoluk** [comment]
The transaction was successfully processed by the Wormhole network, but the client-side transaction submission may have failed. Try clearing your cache and reloading wormholebridge.com to see if the transaction can be completed there. Make sure both wallets are connected.

If wormholebridge.com doesn't work, you can manually submit the signed VAA bytes below to the submitVAA method on the Wormhole contract: https://etherscan.io/address/0xf92cd566ea4864356c5491c177a430c222d7e678#writeContract

---

Digest (for reference only): 7c1d5ec7009f9e12195db12f590317db951b4818246f12e21abc0f0a932cd74f

Signed VAA bytes to submit to the contract:

> 0x01000000010d00c67175e6b54ceca5435453cbdd53b85788c5699217779436ee1ac87cf6411d475da12fa4fdf5e1581bb4caf659cebdfc2864ad9b1d37a6e82f807c25dfa39fa4000190950e5945045df4d7340b98a1276a67fe4afd711fd2aa1dba40eaf4318b484f24ff2a53e40d6c6f8fc28423aca7fef20474e891a53e122f13ada680dffa959901049792372092317355d13995a3d0f91446eb57b546e792e183daea5ba60fffb1576c5fb82a8db893421fb87ea6d30daaa363f022d7710ea8efbf023cc8d959f84001057b40e32b9a064b6a1d32dd5df473b9cd3936ee56ceb44318c276ad3fac9aa7983279a5afac48988e66fc93ad8849ba6f87a442ebe6c49fba8987b7ca29ad84af0006309caa6735851fe96c52d75d96323e44996a457fb8dcda83945b7702fdc6367f2cffb452ba339322499938e62ec9d966d8f1a319a6573df1fb77786b7818f654000797aa6b300b1fc696aa919ff80c5ad95cf24c4b02e49c7b67c6b5275211e20f1b1407e64e142f872b39aa88799e969c7b25fc2ac4b8b566c124070ce1b9e412fe00086f4b9ab2426186445f4cea054f40dde43dccc2fd2de80106b904b7fdb3f095f450e870cd91c166dba4e9f976b698b2a05c35f6a39493ae4e7cbe42628fc0416b01098c5dfd10e12899dd5c5efa0d240904ee2483dea961d6f9de8551e291c349f0b179771c0c035d8c9fa717e2ecae2b20abd691e61ad07072e445d96e49c6df210d010aa84ce84a184fc87ccec06d52a288fbde729eb964ef2a82ccbdd2275dcb36e8c13b7c3b39ffb5fd7dc9f7b3dcc4dec67c32978557ce9832d071dd71d94c3246e2000ba1655dfe8c50d858772f0f644573fa67105e09b66c1459a3bfe9e92b0cba36772665f4bc7ef497778eac34558f19acb4006ea3eb5d7bc262fd422e74a8c24afd000d0c65fe4885524fd79013579a4d8e945c907c896ac1bf692e61b89af6af098ac02119b3577f215c5f502b74f87008c78aaeac0894b78711949e37bb7ad9cb9f5e0010d56a38be1c82d4ae4430568db64aeb336226a9dca9317ecf4e9e6999ccfb48341170f747be45a09500a6845d90c2c12e8ded103860ea5f48e1891feb08a0031b0012c43a4f45c4b83e17eceef65373bf8e26e083aeba4c87d24400ef290be18b8f3c0aecd684a1b6467dd6f1b67c565f00ed6525873db52bed7bb1b5235f0641a0f3016132a754100000700601023c1dea85ee9a01d4788c8f63d3c2c88108c778195b487be645997b3c894d98c1000000000000000000000000ddc60d163015cf5ca1369d557a2ca1cc2de1f1e3020000000000000000000000002260fac5e5542a773aa44fbcfedf7c193bc2c59908000000000000000000000000000000000000000000000000000000000bebc200

**Comment by bellabartok** [comment]
Resolved, thanks!
