### ISSUE TITLE
WETH wormhole does not transfer to Metamask

### ISSUE THREAD

**Issue by jeta92** [certusone/wormhole#386]
WETH does not get back in my metamask wallet after sending it through wormhole. I sent it back from Sol to eth network through wormhole bridge, it does not show on my phantom and has not arrived to my metamask.
BV1NRU5FQvxKgY2e4jL4JKB1hiDrrTYYfhhiJpUJVhkJ

**Comment by leoluk** [comment]
Please provide a transaction hash
