### ISSUE TITLE
Getting started guide

### ISSUE THREAD

**Issue by allenan** [certusone/wormhole#441]
As a developer looking to get familiar with wormhole so that I can contribute, I'd like to be able to replicate the end to end flow locally on the devnet. A good starting point might be a guide that reproduces this demo: https://www.youtube.com/watch?v=9OTTyJ_h4O0. I was able to follow the existing docs to stand up tilt and view the guardian heartbeat in the explorer but feel a little lost as to where to go next. Additionally, is there a discord or some equivalent where I could ask questions as I'm learning? If so it might be worth pointing to that in the readme.

**Comment by leoluk** [comment]
Fully agreed - we need better docs for new devs.

This guide gets you set up with a local devnet: https://github.com/certusone/wormhole/blob/dev.v2/DEVELOP.md (you probably saw this already)

Here's how to run the bridge UI: https://github.com/certusone/wormhole/tree/dev.v2/bridge_ui

Come to our Discord server and we'll be glad to answer any other questions :) https://discord.gg/xsT8qrHAvV

**Comment by leoluk** [comment]
Actually, reopening this issue as a reminder to write those getting started docs

**Comment by allenan** [comment]
Thanks for the pointer to the bridge UI, I hadn't seen that. Are there any other docs that demonstrate using the bridge UI? I guess I'm unclear on which accounts and contracts exist by default, or if I would need to create anything in order be able to test sending tokens through the devnet. I'm happy to contribute to some of this documentation too btw as I learn more.

**Comment by leoluk** [comment]
@allenan Best to ask on Discord. Documentation PRs would be greatly appreciated!

**Comment by evan-gray** [comment]
https://docs.wormholenetwork.com/wormhole/
