### ISSUE TITLE
Eth Lost Bridging to Sol

### ISSUE THREAD

**Issue by MO3454** [certusone/wormhole#463]
I tried to bridge Eth to Sol and it appears to have gone missing. After trying to complete the recovery manually, I still can't receive my funds. It keeps saying  "failed: Error processing Instruction 0: custom program error: 0x0" every-time I hit redeem tokens. 

Eth TX Hash- 0xfbb8c26cbcbb776b9767e2307d8232714550d5ba9ea364a8b2585e5a4c68d29f

 thank you for the help!

**Comment by leoluk** [comment]
Looks like the transfer worked: https://explorer.solana.com/address/Fkr7UT5wQrC741utorDyjJ3BfKDFya97ukjLYMDsSdw7

Make sure to check in the NFT section, Phantom has a bug where it believes Wormhole tokens are pretty pictures.
