### ISSUE TITLE
DAI transfer from Sol to ETH network stucked

### ISSUE THREAD

**Issue by Geor-2736** [certusone/wormhole#465]
Hi,
Can you please help me checking where got my transfer lost?
Sent DAI from Solana to ETH metamask wallet, but it never arrived. 
I was only asked to confirm the transfer from Sol wallet and then it was just hanging saying waiting for Solana confirmation. When checked the recent activity, it says "success", but it has not arrived.
This is the signature:
Signature: 3zjHQ2HT6EWST8YoG1akBJJ8UWrPNo5VzkZ8KMHtXzzRBrpzRt7LyVN1BJpEUu7DiUeHRWwEvTbdYdnj98ckdcYg
and this should be the "success" confirmation.
https://explorer.solana.com/tx/3zjHQ2HT6EWST8YoG1akBJJ8UWrPNo5VzkZ8KMHtXzzRBrpzRt7LyVN1BJpEUu7DiUeHRWwEvTbdYdnj98ckdcYg

I've already cleared the cache, restartet the browser, but no luck.

Thank you,
G.

**Comment by leoluk** [comment]
The transaction was successfully processed by the Wormhole network, but the client-side transaction submission may have failed. Try clearing your cache and reloading https://v1.wormholebridge.com to see if the transaction can be completed there. Make sure both wallets are connected, and select both tokens from the picker.

If v1.wormholebridge.com doesn't work, you can manually submit the signed VAA bytes below to the submitVAA method on the Wormhole contract: https://etherscan.io/address/0xf92cd566ea4864356c5491c177a430c222d7e678#writeContract

Note that Wormhole v2 was recently launched on wormholebridge.com, which fixes the bug you encountered! You will still have to use v1 to complete your in-progress transfer.

You can also try using the third-party https://www.interstellar.tk site to retry your VAA submission.

---

Digest (for reference only): 65ce04c711c7dfb0544a3bd88d99a369a2d0bd6367018bd4afdb634c192d9883

Signed VAA bytes to submit to the contract:

> 0x01000000010d00671a5cf685c1dec2c44eca3e2f16b4fc2d23e1d81a7dea3b69cf971500c8de0a0072b15b198ce7c8268cbbdd44b6bd80520ff282d9c3aed85a2abbb010cfc5a3000123be20ad307b1a892d4d1559d03ab79dfc79085aad0a8d07b1ecfa148bbd9efb7df6872e3cda4247c69bf6d47e305c34c66fe96873bd0b7bac3466a717f67483000286dcc231d479fba364d7a33287ff52756da96ff1ca4fb00e08b0209f7ea0885e791ba1d6fea2a62899e0733522c21b47ba6bd156a2f9066991824e243cb0e9a9000391f0fb0abaf9703b81d9c06a5f2804615d2792af58c3acf2739e3fb7fe4e1f8654827821fdd7c4ffcf81a38d28dad24ccced96c33823e6a00d8f6375203871a400051a21258fd9c30045de3b0c951454abb738a5d9094818b0a2a7c024c42e6c66fb30a11e45138349abea1f2354306fd1b462891296c0a44ad8d735340a836d4f690006a203446eba05936d7ed9a5fe7f5f379221b10cc26f87218f1b04a15be4ee52a40060690ef9d4386ceca76a536f5e6bb2c4965441c183b045add4d128440d76b5000701644679a42dfe6cda95a45b1e7fb3632d650c77dd7cba7ab172d24ede6532c30786933b554931b3afc9eb421f3d50b0e9533b5a90aa77dc87a01b8865701ea80108243aff41c4306b9310968e9c6f9d122967587ed0c144038e5b213c08328c8c0c5eb5ce48caa40530453b32670d91bdaf6e9784da23b83caa88da5c6a785085d9000ae91bda33b40ae2b32348fb97e9e5b931d7e7ac0ebcfdb082393fb6e9512002d7056450366a4e8e91a615eae55a05875452747b7e08fcc64d67c898ebc4b660bc010cbcbf067784fb65d550c6649fcc9115f3fa1432296f7ef476478010b717d800bb57db3c974847afec44540210be596a166e365a039e1b7b65832f3ea209e5649a010dc43f7651cfd529f7189d747479fac9a556d525806160881917c77e4d179a209f569ffe3345d382e0c2cc252e378b8a9d883fce2a55c61b7a49bb6844da84499500109f76ea5eaa68864fc761e2acada67ece2b29a8abad9af465fd5366c863757b0f1e8416131fb9f8915ed47901ba5ef30b1157e2a7e680d46d1b7d8b43568703c60112bd36da427149f54c09e85713824aff5a85cd8f2bd5eed75701d82e19fd7eb4c30ed6b523df9875e6c8b25d448531d7ba92a55f5bd8030161c69992947596f0ed00614a0d9c10000076da0102b5b24600a1f73ef4f913a5146aa2bbade5198f331c532a3a4fb6fa2d9f4f9f4200000000000000000000000018281a5713b251932ecefb8e8a7e52fad3ab3dfa020000000000000000000000006b175474e89094c44da98b954eedeac495271d0f090000000000000000000000000000000000000000000000000000007756e676c2
