### ISSUE TITLE
"wormhole v1 tokens are not eligible for transfer"

### ISSUE THREAD

**Issue by jetlej** [certusone/wormhole#494]
I have wETH and wBTC in my Solana wallet from Wormhole V1. How do I get them back into a form that can be moved back to Ethereum via Wormhole V2? 

I don't see them showing up on Raydium, nor can I transfer them via Wormhole anymore.

**Comment by evan-gray** [comment]
Tokens which are not eligible for migration or do not have swaps available may still be able to be transferred back via https://v1.wormholebridge.com/#/. I would recommend visiting the [discord](https://discord.gg/xsT8qrHAvV) for assistance.
