### ISSUE TITLE
Transfer stuck on "Waiting for Wormhole Network Consensus..."

### ISSUE THREAD

**Issue by marmijo505** [certusone/wormhole#497]
Hello, I have been stuck on the "Waiting for Wormhole Network consensus..." status for a while now. Step 3 looks to have succeeded with transaction https://explorer.solana.com/tx/iZbQHn3UnYXRrvxpUyy8oGkeAprC7ocXp4W19GwFhK8kmBVsw2RjederLVkJ1jD3PKt1yU7ojp5qzKkERsgNm2n

The last transaction in my wallet is: https://explorer.solana.com/tx/3j7BNQbhSq2DFVfv3As8dxFoFcr8NG7vqx8WwZmem2ehQTCNP74r4Rf5MbpvrM4GqUMLfrgik8xVUvokPtduBx6S

I've tried to run the recovery, but when I put the transaction number in, I get the attached issue
![wormhole issue](https://user-images.githubusercontent.com/55031754/134999886-58d36229-81e4-4f7a-9593-c5531afddc24.jpg)

**Comment by evan-gray** [comment]
Hi there! I understand this missed transaction will be picked up in the next update. Heard you followed up on discord, so I'll close this issue here.

**Comment by marmijo505** [comment]
Yes… thanks so much!

MICHAEL ARMIJO
