### ISSUE TITLE
metamask erc20 to phantom ( Sol ) error

### ISSUE THREAD

**Issue by slickrider** [certusone/wormhole#500]
### Discussed in https://github.com/certusone/wormhole/discussions/496

<div type='discussions-op-text'>

<sup>Originally posted by **slickrider** September 27, 2021</sup>
i sent my eth from my metamask to my my phantom wallet ( sol ) and cant redeem my tokens , coins where taken from metamask but not delivered to my phantom wallet

<img width="1680" alt="Screen Shot 2021-09-27 at 2 46 40 PM" src="https://user-images.githubusercontent.com/91293229/134968130-07948f0d-1b36-49d1-9926-8a431f4f7853.png">
</div>

**Comment by evan-gray** [comment]
Hi @slickrider, is it possible that you got to this step without having created an associated token account? An easy way to confirm this is to open the app, select Ethereum and the same token in the source, connect the same wallet for target and see if the "Sent to:" address has a large blue button labeled "Create Associated Token Account". If the button is there, you will have to click it and approve the transaction, then you should be able to complete your transfer here.

**Comment by slickrider** [comment]
Already added a lot of different coins and still stuck , i dont really know whats the coin im suppose to recieved. Please help me

**Comment by slickrider** [comment]
today i tried a new transaction , Create Associated Token Account again and i will able to redeem my tokens , THANKS
