### ISSUE TITLE
Unrecognized Token in Solflare Wallet after Wormhole Bridge transfer

### ISSUE THREAD

**Issue by ajpatt61** [certusone/wormhole#504]
I transferred SRM from metamask to Solflare and the mint address assigned during the transfer resulted in an unrecognized token in my Solflare wallet (doesn't match the SRM address)
How can I get the SRM mint address re-assigned?

**Comment by evan-gray** [comment]
Hi @ajpatt61. When you transferred SRM from Ethereum, you would receive Wormhole v2 wrapped SRM (xnorPhAzWXUczCP3KjU5yDxmKKZi5cSbxytQ1LgE3kG) on Solana, not native SRM (SRMuApVNdxXokk5GT7XD5cUUgXMBCoAz2LHeuAoKWRt) - there should have been a message to that effect. There is no way to "re-assign" the mint, though you may be able to swap or transfer the assets back. I would recommend following up in the [Discord](https://discord.gg/xsT8qrHAvV) if you have questions about the v2 tokens.
