### ISSUE TITLE
Transaction Stuck At Waiting for Wormhole Network Consensus

### ISSUE THREAD

**Issue by amol3335** [certusone/wormhole#506]
https://explorer.solana.com/tx/5h9Ww2du6XHBTMBRGz7zwYhTp6BVPECcwzDtSWyeJrboH32KDYnEbWRSSc2acBayov5souo842myMu3gRzSf5fHm
Transaction Stuck.

**Comment by evan-gray** [comment]
Looks like this transaction was missed by the guardians and should be picked up after their next update. (I think someone replied similarly on Discord)

**Comment by amol3335** [comment]
> Looks like this transaction was missed by the guardians and should be picked up after their next update. (I think someone replied similarly on Discord)

When is this Update scheduled??
