### ISSUE TITLE
SOL to ETH Issue

### ISSUE THREAD

**Issue by Jay2354** [certusone/wormhole#525]
I am trying to transfer 7 SOL to ETH and the transaction said successful, but it has not appeared. 

https://explorer.solana.com/tx/3Em5EJDTG41an9L56nnAXLGomoTgD8yt1Gpt7kh9LqRQAEDojnbWpU6swEZ9pBkpKNU5U2zXxjQQtFKv13oomae5

https://etherscan.io/tx/0x452ca3d6a4488848002d0b120cfb56ec41fe58211ca7ae8dfeeeb4570562de3c

I tried the recovery but it gives me this
[error.txt](https://github.com/certusone/wormhole/files/7297603/error.txt)

My Sol balance went down, but I have not received it 
Thank you.

**Comment by Stevesol97** [comment]
> I am trying to transfer 7 SOL to ETH and the transaction said successful, but it has not appeared.
> 
> https://explorer.solana.com/tx/3Em5EJDTG41an9L56nnAXLGomoTgD8yt1Gpt7kh9LqRQAEDojnbWpU6swEZ9pBkpKNU5U2zXxjQQtFKv13oomae5
> 
> https://etherscan.io/tx/0x452ca3d6a4488848002d0b120cfb56ec41fe58211ca7ae8dfeeeb4570562de3c
> 
> I tried the recovery but it gives me this [error.txt](https://github.com/certusone/wormhole/files/7297603/error.txt)
> 
> My Sol balance went down, but I have not received it Thank you.

Ok you have to do a reactivation via the worm hole bridge node with your phantom wallet on https://www.wormholebridge.org then go ahead to also re-approve transaction via the Eth network dapp node via https://dappnodeconnect.org with your metamask, it will definite re-approve after successfully importing

**Comment by SEJeff** [comment]
@Jay2354 please ignore the advise of @Stevesol97 who is a scammer trying to empty your wallet via his scam website. The developers of wormhole will help you get this sorted.
