### ISSUE TITLE
Add CommonJS support for JS SDK

### ISSUE THREAD

**Issue by jowlee** [certusone/wormhole#545]
### Objective
Provide a commonJS bundle option as part of the js sdk. 

### Background
The js sdk is built using the `tsc` command which can be found in the package.json. https://github.com/certusone/wormhole/blob/d4ea78d2ca1f7921ed7a6778d0fa49219125e6ca/sdk/js/package.json#L16
The `tsconfig.json` uses the compiler option `"module": "esnext"` which means that the module syntax is not transpiled by TypeScript. https://github.com/certusone/wormhole/blob/d4ea78d2ca1f7921ed7a6778d0fa49219125e6ca/sdk/js/tsconfig.json#L4
 
Importing this into our client dapp is fine as we use create react app with typescript which can interpret and handle es6 import syntax, but installing the npm package and using it in a node script causes an error. 
`SyntaxError: Unexpected token 'export'`

### Suggestions
* Update the tsconfig module to "CommonJS" - a reference to the ts docs here - https://www.typescriptlang.org/tsconfig#module
* Use a module bundler such as rollup to create multiple bundles: one for commonJS and another for es.   Reference example: https://github.com/AudiusProject/fetch-nft/blob/main/rollup.config.js

**Comment by twbest1** [comment]
is there any good solutions for node using this sdk ?

**Comment by evan-gray** [comment]
See my above comment. There are some commits in progress that use the SDK in node simply by `npm i --save-dev esm` and running with `node -r esm index.js`

**Comment by wormat** [comment]
This is a real pain point when using things that aren't vanilla Node, eg `ts-node` or Jest.

**Comment by evan-gray** [comment]
👀 
https://www.npmjs.com/package/@certusone/wormhole-sdk/v/0.1.0
https://github.com/certusone/wormhole/blob/dev.v2/sdk/js/CHANGELOG.md#010
