### ISSUE TITLE
Error in npm start

### ISSUE THREAD

**Issue by ChunHuCui** [certusone/wormhole#559]
Hi. I met an error in npm start on the v2-dev branch.
![2021-11-04_01h42_59](https://user-images.githubusercontent.com/68866354/140263905-242fe492-9554-4631-aee6-cb1e74005dff.png)

Could you possibly check this error?
Thank you in advance.

**Comment by evan-gray** [comment]
Could you please verify all of the steps in bridge_ui/README.md and share the output?

```
docker --version
node --version
npm --verison
DOCKER_BUILDKIT=1 docker build --target node-export -f Dockerfile.proto -o type=local,dest=. .
DOCKER_BUILDKIT=1 docker build -f solana/Dockerfile.wasm -o type=local,dest=. solana
npm ci --prefix ethereum
npm ci --prefix sdk/js
npm run build --prefix sdk/js
```
