### ISSUE TITLE
wormholenetwork.com redirects with a 404

### ISSUE THREAD

**Issue by jonathansampson** [certusone/wormhole#561]
Initial requests to https://wormholenetwork.com/ are responded to with an HTTP 404 response. Following this 404, a redirect takes place to https://wormholenetwork.com/en/ (presumably based on what my request headers reveal about my preferred _language_).

This redirect works (it serves a working landing page), but the 404 can cause confusion in some scenarios. For example, the brief 404 causes the Brave Browser (and presumably any browser equipped with WayBack Machine integration) to report the page as _missing_, inviting the user to query for a remotely-cached copy. This is confusing for the user since the landing page is ultimately found, following the redirect.

**Comment by justinschuldt** [comment]
Thanks for reporting, will investigate.

**Comment by VarunaSene** [comment]
Now the issue is solved?
