### ISSUE TITLE
Testnet wormhole is broken

### ISSUE THREAD

**Issue by chrisirhc** [certusone/wormhole#567]
Seems like the Goerli testnet contract isn't working.
Just saw in the Discord that this is expected and being worked on. 

Just creating a ticket to track this.

**Comment by mnguyen-io** [comment]
Testnet is no longer being maintained/used

**Comment by evan-gray** [comment]
Hi @chrisirhc, thanks for creating this issue! Working on bringing up a single-guardian testnet for developers. Should be ready to go in the next few days and I’ll post back details and docs links once I’m able to confirm 🙂

**Comment by evan-gray** [comment]
@chrisirhc testnet is up! https://docs.wormholenetwork.com/wormhole/contracts#testnet
