### ISSUE TITLE
Lost message 1/ec7372995d5cc8732397fb0ad35c0121e0eaa90d26f828a534cab54391b3a4f5/17634

### ISSUE THREAD

**Issue by leoluk** [certusone/wormhole#568]
https://wormhole-v2-mainnet-api.certus.one/v1/signed_vaa/1/ec7372995d5cc8732397fb0ad35c0121e0eaa90d26f828a534cab54391b3a4f5/17634

**Comment by leoluk** [comment]
Plus:

https://wormhole-v2-mainnet-api.mcf.rocks/v1/signed_vaa/1/0def15a24423e1edd1a5ab16f557b9060303ddbab8c803d2ee48f4b78a1cfd6b/300

**Comment by evan-gray** [comment]
I believe these have since been un-lost
