### ISSUE TITLE
Can't redeem token

### ISSUE THREAD

**Issue by Steccas** [certusone/wormhole#570]
HI all! I've tried to transfer some USDC from Solana network to Terra Network (Yes I know I will receive wh tokens and I will have to swap them). On solana side it went well, but unfortunately I can't redeem them and instead of giving me a popup it gives this error:

`rpc error: code = NotFound desc = rpc error: code = NotFound desc = account <account address> not found: key not found`

Yet the account exists, wormhole took it automatically from terra station and I can find it on Terra Finder.

I tried from multiple devices and browsers, same outcome.

My funds are now stuck in a limbo, what can I do? Is this an app issue or I did something wrong?

**Comment by evan-gray** [comment]
Hi @Steccas! Would you mind asking your question on the discord - https://discord.gg/xsT8qrHAvV ? That’s a bit more support focused, tends to be only contributors who check here 🙂

**Comment by Steccas** [comment]
Hi @evan-gray, actually I solved. The wallet never received native tokens (Luna or UST) I sent some and the error disappeared.

So the wallet cannot be used if it is "Virgin", i don't know if it is intended or a bug.

If it's not the issue can be closed.

**Comment by evan-gray** [comment]
Ah, yes you would need some Luna to pay for the transaction costs on Terra (for the redeem). I don’t recall seeing that error before. I guess it’s different for a wallet that’s never been used than one that has but doesn’t have enough funds for the fee. But yes, at this time, you need a wallet with some Luna to pay the fees, so I’ll close this. Thanks for reporting 🙂 glad you got it solved!
