### ISSUE TITLE
PLEASE HELP! Lost all my money in wormhole

### ISSUE THREAD

**Issue by bowie91** [certusone/wormhole#571]
42A1AC9025FC1B5DA1C0BACE36A4A389C0839A3CF8CD51BD072EB7BC4DEF6247

Cannot redeem the UST on terra or solana side please help

**Comment by evan-gray** [comment]
The transaction hash you referenced has failed, which means no funds should have been locked as a result. https://finder.terra.money/mainnet/tx/42A1AC9025FC1B5DA1C0BACE36A4A389C0839A3CF8CD51BD072EB7BC4DEF6247

Not sure what your balances were 3 days ago, but if you’re transferring UST you need to have enough left over to pay the “stability fee / taxes” on the amount you’re sending (in other words, you can’t transfer 100% of your UST.)

In the future, please ask support related questions on the discord - https://discord.gg/xsT8qrHAvV That’s a bit more support focused, tends to be only contributors who check here 🙂
