### ISSUE TITLE
Private keys in repo

### ISSUE THREAD

**Issue by caitsithlord** [certusone/wormhole#582]
I got a file `examples/core/src/core/consts.ts` after cloning the repo and building bridge_ui and it contains private keys to a solana and ethereum wallet.

**Comment by justinschuldt** [comment]
Hey @caitsithlord , thanks for sharing your concern. Their are keys in several places in this repo that are used for bootstrapping and interacting with the local development environment. These keys are used with the local chains that Tilt creates. You can also use the keys to interact with the local network via Metamask and Phantom. See [devnet.md](https://github.com/certusone/wormhole/blob/dev.v2/docs/devnet.md). The keys you mentioned are intended to be there.
