### ISSUE TITLE
bridge from BSC to Polygon

### ISSUE THREAD

**Issue by gianrnw** [certusone/wormhole#668]
Hello, 
I have been trying to use the sdk to bridge some MATIC from BSC to Polygon but I cannot figure out what I should put as WORMHOLE_RPC_HOST. I have been looking and searching around but I did not find any. Could anyone help me with that?

**Comment by evan-gray** [comment]
Hi @gianrnw ! You can find the public guardian RPC hosts here https://docs.wormholenetwork.com/wormhole/contracts#public-guardian-rpcs

May I also suggest using getSignedVAAWithRetry if you are looking to poll 🙂 
You can check out https://github.com/certusone/wormhole/blob/dev.v2/examples/core/src/commonWorkflows.ts, though there are other examples around our codebase
