### ISSUE TITLE
Cannot send weUSDT from BSC to Solana?

### ISSUE THREAD

**Issue by phuongnd08** [certusone/wormhole#673]
I bridged USDT from Solana to BSC, which I received weUSDT in my BSC account. Now I want to send it back but https://wormholebridge.com/#/transfer won't let me. Please advice.

**Comment by evan-gray** [comment]
Hi @phuongnd08 could you provide some more detail? Do you receive an error when trying to send? I would recommend taking your issue to the [Wormhole Discord](https://discord.gg/xsT8qrHAvV) support channel where the community managers can help out. GitHub issues are primarily reviewed by developers 🙂

**Comment by phuongnd08** [comment]
Sorry, my bad, i entered the wrong contract address. Would recommend to list weUSDT for bridging from bsc to prevent confusion
