### ISSUE TITLE
Funds stuck in Wormhole??

### ISSUE THREAD

**Issue by kidkaos76** [certusone/wormhole#709]
***Fixed, had to "redeem 3x but finally got the funds*** I've used Wormhole before and haven't run into this issue.  I just sent BSC BUSD to SOL using Wormhole.  Got all the way through approving Phantom the several times and it gave me errors.  Now the funds are missing in MetaMask and I can't find them anywhere on the Solana end?  I even tried redeem and it's not working.  Anything I can do to try and get my funds? I even looked on Saber and Mercuri for the wrapped token and nothing.

**Comment by evan-gray** [comment]
Glad you managed to get your transactions through. Sounds like users across the Solana ecosystem were struggling with low throughput today 🙁
