### ISSUE TITLE
Tokens Approved, Transfer Failed, Now Missing from MM

### ISSUE THREAD

**Issue by Bobby10009** [certusone/wormhole#714]
Hi - I've had tokens approved to send via wormhole, yet the transfer of tokens failed. Now they aren't showing up in either wallet.

**Comment by evan-gray** [comment]
Hi @Bobby10009, please ask support related questions on the discord - https://discord.gg/wormholecrypto The wormhole-support channel there is a bit more support focused and the community managers should be able to help, tends to be only contributors who check here 🙂 You might be able to try recovering via https://wormholebridge.com/#/redeem

**Comment by Rajubrar13** [comment]
I have bridged the wormhole from polygon to ETH but it is not showing anywhere yet. When I checked the wormhole, nothing was visible there, nothing was there, I don't know where my BBL token has gone

**Comment by Rajubrar13** [comment]
My evm address is 0xd78b4D0e7D4f27636bF1975D2EDaC60699464686
