### ISSUE TITLE
Why are ERC-721 URI lengths capped at 200? 💭

### ISSUE THREAD

**Issue by almndbtr** [certusone/wormhole#715]
Hello, @certusone!

I'm opening an issue to fulfill my own curiosity, after hitting this message while attempting to bridge one of my NFTs from Ethereum to Solana.

I see that https://github.com/certusone/wormhole/pull/675 was recently merged in to enforce this cap, but I couldn't find any relevant issue or thread that explains why the change was made. I'm wondering if anyone has that context? I'm not pressing for a higher cap by any means -- really just asking to understand. 🙇‍♂️

https://github.com/certusone/wormhole/blob/7f74392a91325dd2012e5454432a77233bdc1e80/bridge_ui/src/store/selectors.ts#L98-L103

**Comment by evan-gray** [comment]
Hi! There was an earlier change merged to the smart contract that included a comment, but essentially, Solana only supports URI lengths up to 200 bytes and the intention was to enforce that restriction throughout the NFT bridge protocol (a keen eye may notice that the original payload only left a u8 for uri length as well). See #628

**Comment by almndbtr** [comment]
@evan-gray Ah, thank you so much! I appreciate the context. 💎

**Comment by evan-gray** [comment]
Sure thing, thanks for asking!
