### ISSUE TITLE
devnet gives an error because of certificate issue

### ISSUE THREAD

**Issue by alicantutumlu** [certusone/wormhole#806]
GetSignedVAA function gives an error like "ERR_CERT_REVOKED". The website has invalid certificate: https://wormhole-v2-testnet-api.certus.one/publicrpc.v1.PublicRPCService/GetSignedVAA

Could you solve the problem?

**Comment by leoluk** [comment]
Background: https://www.theregister.com/2022/01/26/lets_encrypt_certificates/

It's fixed now :pray:
