### ISSUE TITLE
Support ERC-721

### ISSUE THREAD

**Issue by leoluk** [certusone/wormhole#85]
This is a placeholder ticket for ERC-721 NFT wrapping support. Our team is not planning to implement this, but the project is open to contributions that add such support. If you plan to work on this, please reach out first (like by commenting on this issue or the #wormhole channel on the Solana Discord server).

Rough outline on what is needed:

- A stable and generally accepted ERC-721 equivalent on Solana.
- Wrapper contracts on Ethereum and Solana.
- A new VAA message type and implementations in the Eth and Solana contracts.
- Bridge node support for the new message type.
- Auditing the changes.

Depending on what mainnet upgrade paths will look like, it may also require a separate bridge contract on Ethereum (#13).

**Comment by pindaroso** [comment]
This sounds interesting. How high of a priority is this?

**Comment by leoluk** [comment]
Done! :tada:
