### ISSUE TITLE
terra: terra VAA submission is attempted even with terra support disabled

### ISSUE THREAD

**Issue by leoluk** [certusone/wormhole#97]
Needs to check for terraSupport in observation loop.

**Comment by ysavchenko** [comment]
I believe it is already fixed by this line:
https://github.com/certusone/wormhole/blob/master/bridge/pkg/processor/observation.go#L220
@leoluk can you please verify?

**Comment by leoluk** [comment]
Yeah, I think we should change it to rely on the main `terraSupport` flag but other than that this should be fine.

**Comment by leoluk** [comment]
Fixed: https://github.com/certusone/wormhole/commit/106fecca0049bcf8b9f0e368cad4be380d2364d5
